### PR TITLE
Make live reload work in Chrome without console error. Fixes #60

### LINKED ISSUE #60: With LiveReload enabled Chrome shows console error on markdown preview
Hi, 

**TL;DR** I'm sending a PR on this.

I'm using newest version of LiveReload & MarkdownPreview.
After enabling LiveReloads 'Simple Reload', then generating the preview HTML from my markdown, Chrome shows the following error in the console:

```
14:31:04.213 39.html:1106 A parser-blocking, cross site (i.e. different eTLD+1) script, 
http://localhost:35729/livereload.js?snipver=1, is invoked via document.write. 
The network request for this script MAY be blocked by the browser in this or a 
future page load due to poor network connectivity. If blocked in this page load, 
it will be confirmed in a subsequent console message. 
See https://www.chromestatus.com/feature/5718547946799104 for more details.

(anonymous) @ 39.html:1106
``` 

The cited line HTML number has this code:
``` javascript
document.write('<script src="http://' +  (location.host || 'localhost').split(':')[0] +
  ':35729/livereload.js?snipver=1"></' +'script>')
``` 

StackOverflow says Chrome now mandatory needs `async` with `document.write`:
https://stackoverflow.com/a/39610983

I tried a local fix inside `markdown_preview.py` and the error is gone, while the live reload functionality is still working. 

So, I'm sending a PR soon...
Thanks for your work in this cool Plugin!

### PR DESCRIPTION
**Pull request by derwok**
Details see https://stackoverflow.com/a/39610983

### CODE REVIEW

**Comment by facelessuser** [comment]
Does this work in other browsers too? I believe I went down this road before with async. I don't recall if there were issues in other browsers, or if it just got lost in a code refactor.

**Comment by derwok** [comment]
Hi,
Before the fix the console error did only show up in Chrome.
After the `async` fix I can confirm that LiveReload + MarkdownPreview work as expected in
* Mac
  * Chrome 71
  * FireFox 63
  * Safari 11.1.2
* Windows
  * Chrome 70

**Comment by facelessuser** [comment]
Okay, looking closer at this, it now makes since. We were already using async, but not in the script tag we were writing to the document...this makes much more sense now. Thanks for the PR!

**Comment by derwok** [comment]
You're welcome. 
This was only a microscopic contribution compared to the huge effort that already went into this great package! Really appreciate it!

**Pull request merged**
