### PR TITLE
Update font to match GitHub

### PR DESCRIPTION
**Pull request by kennith**
This merge request update font-family and font-size to match with GitHub. 

# Updated:
- pre
- .markdown-body
- .markdown-body code
- .markdown-body kbd
- .markdown-body pre

### CODE REVIEW

**Comment by facelessuser** [comment]
@kennith, Thanks for the pull request. Normally this CSS is synced with https://github.com/sindresorhus/github-markdown-css. I may just merge this, or I may look at resyncing  the CSS. I'll have to see, but one way or the other, I'll update this.

**Comment by facelessuser** [comment]
@gir-bot add S: needs-decision
@gir-bot retrigger auto-labels

**Comment by kennith** [comment]
> @kennith, Thanks for the pull request. Normally this CSS is synced with https://github.com/sindresorhus/github-markdown-css. I may just merge this, or I may look at resyncing the CSS. I'll have to see, but one way or the other, I'll update this.

@facelessuser OK. I can do a PR in https://github.com/sindresorhus/github-markdown-css instead. Let me know which works better.

**Comment by facelessuser** [comment]
You can head down that road if you'd like. It's not a simple drop in as there is a couple of things we manually put in for our own preview, but feel free to take a look. Moving forward, we should probably add some comments to note what we specifically add to make the process easier.

**Comment by facelessuser** [comment]
Bot should look at master now...let's try

@gir-bot retrigger all

**Comment by facelessuser** [comment]
@kennith, I think #97 should do what you want. There are very few changes to the what we sync up to. I had to refresh myself, but it appears to work good.

**Pull request closed without merging**
